# Generated by Django 5.0 on 2024-02-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useridpas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
